// <auto-generated />
using System;
using EventMonitorService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventMonitorService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250312120424_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("EventMonitorService.AppDbEventInstance", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .HasDatabaseName("IX_AppDbEventInstance_Created");

                    b.ToTable("WinEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
